vlc:
  start: true
  host: "localhost"
  port: 8080
  password: "test"
  extraintf: "http,luaintf"
  options:
    - "--no-video-title-show"
    #    - "--start-paused"
    #    - "--fullscreen"
  path:
    #    win: 'C:\Program Files\VideoLAN\VLC\vlc.exe'
    win: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'
    macos: '/Applications/VLC.app/Contents/MacOS/VLC'
    linux: '/usr/bin/vlc'
scheduling:
  path: ./scheduling/**.yaml
  outDir: ./build
  outPriorityLevel: 1000
  polling_time: 0.1
